# you need to have soil, climate, elevation and crop mask (spatial data with the same resolution and grid)

# Please don't use underscore (_) to name the id of CropManagement records in CropManagement Table

[CropManagement_by_scratch]
# 1:yes 0:No
# cropmanagement = cultivars * sowingdate * sowingdensity * organic_fertilization * irrigation * inorganic_fertilization * cropresidue
crop_management=0 # TODO Not completed yet


[spatialized_features]
s_variety=0  # 1:yes 0:No
s_fert=0
s_irr=0
s_sowing=0
s_density=0

[crop_mask_options]
# 1: use a crop mask file 0: Do not use a crop mask
cropmask=1


[variety_settings]
# if variety is spatialized, specify the correspondance of the variety_id in CropManagement table associated with the different varieties in the spatialized variety file (as a dictionary)
variety_dict={"2.0":"1.10","3.0":"2.1"}
### which varieties in crop management table you would like to simulate
variety=("1.10") # use () to keep all the varieties in CropManagement table

[model_options]
models=("dssat")  # ("stics" "celsius" "dssat") # or ("celsius") for only celsius simulation

[sowing_options]
# 1) use gridded sowing date estimated by Celsius as inputs of STICS and DSSAT simulations SD=1
# 2) use fixed sowing date SD=0 # Use also this option for automatic planting management. ANd in this case, change the parameters of the model
# 3) use a list of sowing dates SD=3
# 4) use a gridded sowing date file SD=455 #example Optimal sowing date
SD=3
#SW=(180 250)
SW=(10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360) # list of sowing dates for option 3

[initial_conditions]
# which initial conditions you would like to simulate
initcond=1

[soil_settings]
# use a gridded soil texture file. in this case textclass = 1
textclass=1
# if 0: use a fixed soil texture for all the simulations
soilTextureType="Loamy Sand"


[simulation_options]
# 1- WS and NS
# 2- WS 
# 3- NS
# 4- Potential
simoption=(2)

[fertilization_options]
#fertilization options # give the list of fertilization options you would like to simulate In CropManagement table InoFertiPolicyCode column
fertioption=(0) # use () to keep all the fertilization option in CropManagement table

[irrigation_options]
# Future irrigation options here

[simulation_dates]
# start and end date of the simulation if the sowing date is fixed
startd=270 # 1st October
endd=70 # 10th March
# start and end date of the simulation if the sowing date is estimated
start_sowing=30  # number of days before sowing date to start the simulation
end_sowing=125 # number of days after sowing date to end the simulation

[extraction_options]
doExtract=0 # 1:yes 0:No # if you want to extract an area of interest
#bound=(-17 13.25 -14.5 15.5)  # Sen reduit
#bound=(-18 -35 52 28)
bound=(30 -8 32 -7)
#bound=(-6.675 5.225 2.175 13.175)
shapefile=0 #1 used shapefile instead of boundary limits

[year_range]
# specify the year range of the simulation
mini=1991
maxi=2000

[testoptions]
# 1:yes 0:No
testoption=0

[]
